
attributes:
  ORGANIZATIONNAME: "Vitor Costa"

options:
  preGenCommand: swiftgen
  developmentLanguage: "pt-BR"
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "10.0"

name: PitchPerfect

targets:
  PitchPerfect:
    type: application
    platform: iOS
    info:
      path: PitchPerfect/Supporting Files/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
        UIRequiresFullScreen: true
    sources: 
      - path: PitchPerfect
        excludes:
          - "**/.gitkeep"

    dependencies:
      - carthage: TinyConstraints
      - carthage: XCoordinator

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: cc.vitorcosta.pitchperfect

    preBuildScripts:
      - name: Swiftgen
        script: swiftgen
      - name: Swiftlint
        script: swiftlint
    