
attributes:
  ORGANIZATIONNAME: "Vitor Costa"

options:
  preGenCommand: swiftgen
  developmentLanguage: "pt-BR"
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "10.0"

name: PitchPerfect

targets:
  PitchPerfect:
    type: application
    platform: iOS

    info:
      path: PitchPerfect/Supporting Files/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
        UIRequiresFullScreen: true
        CFBundleDisplayName: "Pitch Perfect"
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)

    sources: 
      - path: PitchPerfect
        excludes:
          - "**/.gitkeep"

    dependencies:
      - carthage: TinyConstraints
      - carthage: XCoordinator

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: costa.vitor.PitchPerfect
        MARKETING_VERSION: "2.0.0" # App's Version
        CURRENT_PROJECT_VERSION: "1" # Build number
        DEVELOPMENT_TEAM: 87JB6QS95U

    preBuildScripts:
      - name: Swiftgen
        script: swiftgen
      - name: Swiftlint
        script: swiftlint
    